/*
 * Desktop host — the SDL layer over the portable QuickJS host core (er_runtime). It opens an SDL
 * window + the SDL backend, resolves the app to run (a bundle file or a built-in fallback), and drives
 * the frame loop (input → touch, pump, commit, present, tick). Everything JS-side — context lifecycle,
 * console/screen/persist globals, eval/reset/error overlay — lives in er_runtime (bridges/quickjs),
 * shared with MCU firmware. main() is a thin driver; the simulator adds watch + reload on er_host_step.
 */

/* Must be defined before any SDL header to disable SDL's main() macro on Windows. */
#define SDL_MAIN_HANDLED

#include "host.h"

#include "er_runtime.h"
#include "er_scene.h"
#include "native_renderer.h"
#include "sdl_backend.h"

#if defined(ER_HAVE_BAKED_ASSETS)
#include "assets.generated.h" /* generated by `npm run build`: er_register_assets() — baked images + fonts */
#endif

#include <SDL2/SDL.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/*----------------------------------------------------------------------------------------------------------------------
 - Variables: Private
 ---------------------------------------------------------------------------------------------------------------------*/

/**
 * @brief Built-in fallback app, evaluated when no bundle is available next to the executable.
 *
 * Exercises the marshalling layer (flex layout, colors, border radius, text, press events) entirely
 * from JS through the NativeUI bridge — a self-contained "the host works" screen.
 */
static const char* k_default_app =
    "const W = screen.width, H = screen.height;\n"
    "const root = NativeUI.createNode('View');\n"
    "NativeUI.setProps(root, { width: W, height: H, backgroundColor: '#111927',\n"
    "                          flexDirection: 'column', padding: 16, gap: 12 });\n"
    "const title = NativeUI.createNode('Text');\n"
    "NativeUI.setProps(title, { text: 'Hello from QuickJS', color: 'white', fontSize: 24 });\n"
    "NativeUI.appendChild(root, title);\n"
    "const subtitle = NativeUI.createNode('Text');\n"
    "NativeUI.setProps(subtitle, { text: 'Tap a card', color: '#9aa5b1', fontSize: 16 });\n"
    "NativeUI.appendChild(root, subtitle);\n"
    "const row = NativeUI.createNode('View');\n"
    "NativeUI.setProps(row, { flexDirection: 'row', gap: 12, marginTop: 8 });\n"
    "NativeUI.appendChild(root, row);\n"
    "const cards = [ { label: 'CPU', color: '#2a9d8f' },\n"
    "                { label: 'MEM', color: '#e94560' },\n"
    "                { label: 'NET', color: '#f4a261' } ];\n"
    "for (let i = 0; i < cards.length; i++) {\n"
    "    const card = NativeUI.createNode('Pressable');\n"
    "    NativeUI.setProps(card, { flex: 1, height: 120, backgroundColor: cards[i].color,\n"
    "                              borderRadius: 10, padding: 12, justifyContent: 'flex-end' });\n"
    "    NativeUI.setEvent(card, 'onPress', () => {\n"
    "        NativeUI.setProps(subtitle, { text: 'Pressed ' + cards[i].label,\n"
    "                                      color: '#ffd166', fontSize: 16 });\n"
    "        console.log('pressed', cards[i].label);\n"
    "    });\n"
    "    const lbl = NativeUI.createNode('Text');\n"
    "    NativeUI.setProps(lbl, { text: cards[i].label, color: 'white', fontSize: 20, fontWeight: 'bold' });\n"
    "    NativeUI.appendChild(card, lbl);\n"
    "    NativeUI.appendChild(row, card);\n"
    "}\n"
    "NativeUI.setRoot(root);\n"
    "NativeUI.commit();\n"
    "console.log('App built UI at', W + 'x' + H, '- tap a card');\n";

/*----------------------------------------------------------------------------------------------------------------------
 - Functions: Private — file helpers
 ---------------------------------------------------------------------------------------------------------------------*/

/**
 * @brief Reads an entire file into a newly allocated, null-terminated buffer.
 *
 * @param[in]  path     Filesystem path to read.
 * @param[out] out_len  Receives the byte length (excluding the appended terminator).
 *
 * @return Heap buffer the caller must free(), or NULL if the file could not be read.
 */
static char* read_file(const char* path, size_t* out_len)
{
    FILE* f = fopen(path, "rb");
    if (!f)
    {
        return NULL;
    }
    fseek(f, 0, SEEK_END);
    const long n = ftell(f);
    fseek(f, 0, SEEK_SET);
    if (n < 0)
    {
        fclose(f);
        return NULL;
    }
    char* buf = (char*)malloc((size_t)n + 1);
    if (!buf)
    {
        fclose(f);
        return NULL;
    }
    const size_t rd = fread(buf, 1, (size_t)n, f);
    fclose(f);
    buf[rd] = '\0';
    *out_len = rd;
    return buf;
}

/**
 * @brief Returns true when a path ends in ".qbc" (a compiled bytecode blob).
 *
 * @param[in] path  File path.
 *
 * @return true for a bytecode path, false for JS source.
 */
static bool is_bytecode_path(const char* path)
{
    const size_t n = strlen(path);
    return n >= 4 && strcmp(path + n - 4, ".qbc") == 0;
}

/**
 * @brief Returns true when a path ends in ".erpkg" (an ERCF config container).
 *
 * @param[in] path  File path.
 *
 * @return true for a container path.
 */
static bool is_container_path(const char* path)
{
    const size_t n = strlen(path);
    return n >= 6 && strcmp(path + n - 6, ".erpkg") == 0;
}

/*----------------------------------------------------------------------------------------------------------------------
 - Functions: Public
 ---------------------------------------------------------------------------------------------------------------------*/

bool er_host_start(const ErHostConfig* cfg, ErHost* host)
{
    memset(host, 0, sizeof(*host));

    SDL_SetMainReady();
    if (SDL_Init(SDL_INIT_VIDEO) != 0)
    {
        SDL_Log("SDL_Init failed: %s", SDL_GetError());
        return false;
    }

    host->window = SDL_CreateWindow(cfg->title ? cfg->title : "embedded-react",
                                    SDL_WINDOWPOS_CENTERED,
                                    SDL_WINDOWPOS_CENTERED,
                                    cfg->width,
                                    cfg->height,
                                    SDL_WINDOW_SHOWN | SDL_WINDOW_ALLOW_HIGHDPI);
    if (!host->window)
    {
        SDL_Log("SDL_CreateWindow failed: %s", SDL_GetError());
        SDL_Quit();
        return false;
    }

    host->renderer = SDL_CreateRenderer(host->window, -1, SDL_RENDERER_ACCELERATED | SDL_RENDERER_PRESENTVSYNC);
    if (!host->renderer)
    {
        SDL_Log("SDL_CreateRenderer failed: %s", SDL_GetError());
        SDL_DestroyWindow(host->window);
        SDL_Quit();
        return false;
    }

    host->phys_w = cfg->width;
    host->phys_h = cfg->height;
    SDL_GetRendererOutputSize(host->renderer, &host->phys_w, &host->phys_h);
    host->dpi_scale = (float)host->phys_w / (float)cfg->width;

    if (!er_sdl_backend_init(host->renderer, host->phys_w, host->phys_h))
    {
        SDL_Log("er_sdl_backend_init failed");
        SDL_DestroyRenderer(host->renderer);
        SDL_DestroyWindow(host->window);
        SDL_Quit();
        return false;
    }

    /* Hand the app's baked assets (images + fonts) to the engine now that the backend init above set
     * up the registries. Generated by `npm run build`; absent before the first build. */
#if defined(ER_HAVE_BAKED_ASSETS)
    er_register_assets();
#endif

    /* Boot the portable QuickJS host core: bridge + console (→ stdout) + screen [+ __erPersist]. */
    const ErRuntimeConfig rt = {
        .screen_width = host->phys_w,
        .screen_height = host->phys_h,
        .screen_scale = host->dpi_scale,
        .install_persist = cfg->persist,
        .log = NULL, /* stdout */
    };
    if (!er_runtime_init(&rt))
    {
        SDL_Log("er_runtime_init failed");
        er_sdl_backend_destroy();
        SDL_DestroyRenderer(host->renderer);
        SDL_DestroyWindow(host->window);
        SDL_Quit();
        return false;
    }

    host->running = true;
    host->prev_ticks = SDL_GetTicks();
    return true;
}

bool er_host_load_app(ErHost* host, const char* explicit_path)
{
    (void)host;
    /* Choose the app to run, in priority order:
     *   1. an explicit path (.erpkg = config container, .qbc = bytecode, else source),
     *   2. a config container (app.erpkg) next to the executable — the universal "a config" path,
     *   3. the compiled bytecode bundle (app.bundle.qbc) next to the executable,
     *   4. the source bundle (app.bundle.js) next to the executable,
     *   5. the built-in fallback JS app.
     */
    char* loaded = NULL;
    const char* app_src = k_default_app;
    size_t app_len = strlen(k_default_app);
    const char* app_name = "<builtin-app>";
    bool app_bytecode = false;
    bool app_container = false;

    if (explicit_path)
    {
        size_t len = 0;
        loaded = read_file(explicit_path, &len);
        if (loaded)
        {
            app_src = loaded;
            app_len = len;
            app_name = explicit_path;
            app_container = is_container_path(explicit_path);
            app_bytecode = is_bytecode_path(explicit_path);
        }
        else
        {
            SDL_Log("could not read '%s'; falling back to the bundled app", explicit_path);
        }
    }
    if (!loaded)
    {
        char* base = SDL_GetBasePath();
        if (base)
        {
            char path[1024];
            size_t len = 0;
            /* Prefer a config container (bytecode + its assets in one verified blob), then the bare
               bytecode blob (no parser, faster boot than source), then the source bundle. */
            snprintf(path, sizeof(path), "%sapp.erpkg", base);
            loaded = read_file(path, &len);
            if (loaded)
            {
                app_src = loaded;
                app_len = len;
                app_name = "app.erpkg";
                app_container = true;
            }
            else
            {
                snprintf(path, sizeof(path), "%sapp.bundle.qbc", base);
                loaded = read_file(path, &len);
                if (loaded)
                {
                    app_src = loaded;
                    app_len = len;
                    app_name = "app.bundle.qbc";
                    app_bytecode = true;
                }
                else
                {
                    snprintf(path, sizeof(path), "%sapp.bundle.js", base);
                    loaded = read_file(path, &len);
                    if (loaded)
                    {
                        app_src = loaded;
                        app_len = len;
                        app_name = "app.bundle.js";
                    }
                }
            }
            SDL_free(base);
        }
    }

    /* Make the chosen path explicit — otherwise a silent fall-back (e.g. the precompiler wasn't built,
       so app.bundle.qbc is missing) looks identical at runtime. */
    SDL_Log("running %s (%s)", app_name, app_container ? "container" : app_bytecode ? "bytecode" : "source");

    bool ok;
    if (app_container)
    {
        /* The container buffer is referenced (asset pixels/font bitmaps point into it), so it must
           outlive the app — keep `loaded` alive deliberately (this host runs one app per process; a
           reload re-reads the file). */
        const ErContainerStatus st = er_runtime_load_container(app_src, app_len);
        if (st != ER_CONTAINER_OK)
        {
            SDL_Log("config rejected: %s", er_runtime_container_status_str(st));
        }
        ok = (st == ER_CONTAINER_OK);
        return ok; /* intentionally not freeing `loaded` */
    }
    ok = app_bytecode ? er_runtime_load_bytecode(app_src, app_len) : er_runtime_load_source(app_src, app_len, app_name);
    free(loaded);
    return ok;
}

bool er_host_reload(ErHost* host, const char* explicit_path)
{
    /* Live reload (full remount): er_runtime drops the JS context + resets the engine, then we re-run
     * the app. Component state is not preserved (use usePersistentState). Registered images/fonts
     * survive the reset, so baked assets keep resolving. */
    er_runtime_reset();
    return er_host_load_app(host, explicit_path);
}

void er_host_clear_persist(void)
{
    er_runtime_clear_persist();
}

void er_host_show_error(ErHost* host)
{
    (void)host;
    er_runtime_show_error(); /* the next er_host_step commit paints it */
}

int er_host_event_px(const ErHost* host, int logical)
{
    return (int)((float)logical * host->dpi_scale + 0.5f);
}

bool er_host_step(ErHost* host)
{
    SDL_Event ev;
    while (SDL_PollEvent(&ev))
    {
        if (ev.type == SDL_QUIT)
        {
            host->running = false;
        }
        else if (ev.type == SDL_KEYDOWN && ev.key.keysym.sym == SDLK_ESCAPE)
        {
            host->running = false;
        }
        else if (ev.type == SDL_KEYDOWN && ev.key.keysym.sym == SDLK_r)
        {
            host->reload_requested = true; /* the simulator acts on this; the demo ignores it */
        }
        else if (ev.type == SDL_MOUSEBUTTONDOWN && ev.button.button == SDL_BUTTON_LEFT)
        {
            embedded_renderer_touch(
                0, ER_TOUCH_DOWN, er_host_event_px(host, ev.button.x), er_host_event_px(host, ev.button.y));
        }
        else if (ev.type == SDL_MOUSEBUTTONUP && ev.button.button == SDL_BUTTON_LEFT)
        {
            embedded_renderer_touch(
                0, ER_TOUCH_UP, er_host_event_px(host, ev.button.x), er_host_event_px(host, ev.button.y));
        }
        else if (ev.type == SDL_MOUSEMOTION && (ev.motion.state & SDL_BUTTON_LMASK))
        {
            embedded_renderer_touch(
                0, ER_TOUCH_MOVE, er_host_event_px(host, ev.motion.x), er_host_event_px(host, ev.motion.y));
        }
    }

    /* Service Promises and setTimeout/setInterval before painting, so timer/async-driven state
       updates land in this frame's commit. The engine clock used by timers was advanced by last
       frame's embedded_renderer_tick. */
    er_runtime_pump();

    er_commit();
    er_sdl_present();

    const uint32_t now = SDL_GetTicks();
    embedded_renderer_tick(now - host->prev_ticks);
    host->prev_ticks = now;

    return host->running;
}

void er_host_run(ErHost* host)
{
    host->prev_ticks = SDL_GetTicks();
    while (er_host_step(host))
    {
        /* step until quit */
    }
}

void er_host_shutdown(ErHost* host)
{
    er_runtime_shutdown();
    er_sdl_backend_destroy();
    if (host->renderer)
    {
        SDL_DestroyRenderer(host->renderer);
        host->renderer = NULL;
    }
    if (host->window)
    {
        SDL_DestroyWindow(host->window);
        host->window = NULL;
    }
    SDL_Quit();
}
