/*
 * Desktop host core — the reusable SDL + QuickJS + engine runtime shared by the desktop demo
 * (main.c) and, later, the simulator (see /SIMULATOR.md). It brings up an SDL window and the SDL
 * backend, boots a QuickJS context with the NativeUI bridge + host globals (console, screen),
 * resolves and evaluates a JS app, and drives the frame loop (input → touch, pump, commit, present,
 * tick). main() is just a thin driver over this; the simulator will add a watch + reload layer on
 * top of the same steppable API (er_host_step).
 */

/* Must be defined before any SDL header to disable SDL's main() macro on Windows. */
#define SDL_MAIN_HANDLED

#include "host.h"

#include "er_scene.h"
#include "native_renderer.h"
#include "native_ui_bridge.h"
#include "quickjs.h"
#include "sdl_backend.h"

#if defined(ER_HAVE_BAKED_ASSETS)
#include "assets.generated.h" /* generated by `npm run build`: er_register_assets() — baked images + fonts */
#endif

#include <SDL2/SDL.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/*----------------------------------------------------------------------------------------------------------------------
 - Variables: Private
 ---------------------------------------------------------------------------------------------------------------------*/

/**
 * @brief Built-in fallback app, evaluated when no bundle is available next to the executable.
 *
 * Exercises the marshalling layer (flex layout, colors, border radius, text, press events) entirely
 * from JS through the NativeUI bridge — a self-contained "the host works" screen. `screen` is
 * injected by the host before eval.
 */
static const char* k_default_app =
    "const W = screen.width, H = screen.height;\n"
    "const root = NativeUI.createNode('View');\n"
    "NativeUI.setProps(root, { width: W, height: H, backgroundColor: '#111927',\n"
    "                          flexDirection: 'column', padding: 16, gap: 12 });\n"
    "const title = NativeUI.createNode('Text');\n"
    "NativeUI.setProps(title, { text: 'Hello from QuickJS', color: 'white', fontSize: 24 });\n"
    "NativeUI.appendChild(root, title);\n"
    "const subtitle = NativeUI.createNode('Text');\n"
    "NativeUI.setProps(subtitle, { text: 'Tap a card', color: '#9aa5b1', fontSize: 16 });\n"
    "NativeUI.appendChild(root, subtitle);\n"
    "const row = NativeUI.createNode('View');\n"
    "NativeUI.setProps(row, { flexDirection: 'row', gap: 12, marginTop: 8 });\n"
    "NativeUI.appendChild(root, row);\n"
    "const cards = [ { label: 'CPU', color: '#2a9d8f' },\n"
    "                { label: 'MEM', color: '#e94560' },\n"
    "                { label: 'NET', color: '#f4a261' } ];\n"
    "for (let i = 0; i < cards.length; i++) {\n"
    "    const card = NativeUI.createNode('Pressable');\n"
    "    NativeUI.setProps(card, { flex: 1, height: 120, backgroundColor: cards[i].color,\n"
    "                              borderRadius: 10, padding: 12, justifyContent: 'flex-end' });\n"
    "    NativeUI.setEvent(card, 'onPress', () => {\n"
    "        NativeUI.setProps(subtitle, { text: 'Pressed ' + cards[i].label,\n"
    "                                      color: '#ffd166', fontSize: 16 });\n"
    "        console.log('pressed', cards[i].label);\n"
    "    });\n"
    "    const lbl = NativeUI.createNode('Text');\n"
    "    NativeUI.setProps(lbl, { text: cards[i].label, color: 'white', fontSize: 20, fontWeight: 'bold' });\n"
    "    NativeUI.appendChild(card, lbl);\n"
    "    NativeUI.appendChild(row, card);\n"
    "}\n"
    "NativeUI.setRoot(root);\n"
    "NativeUI.commit();\n"
    "console.log('App built UI at', W + 'x' + H, '- tap a card');\n";

/**
 * @brief Last uncaught JS error (message + stack), captured by host_report for the error overlay.
 */
static char s_last_error[512] = "";

/**
 * @brief Error-overlay app: builds a red "JS error" screen from the `__error` global. Evaluated by
 *        er_host_show_error so a failed load/reload shows the error on screen (RN redbox style)
 *        instead of leaving a blank or stale window. Reuses the NativeUI marshalling path.
 */
static const char* k_error_app =
    "const W = screen.width, H = screen.height;\n"
    "const msg = (typeof __error === 'string' && __error) ? __error : 'Unknown error';\n"
    "const root = NativeUI.createNode('View');\n"
    "NativeUI.setProps(root, { width: W, height: H, backgroundColor: '#7a0b0b',\n"
    "                          flexDirection: 'column', padding: 24, gap: 12 });\n"
    "const title = NativeUI.createNode('Text');\n"
    "NativeUI.setProps(title, { text: 'JS error', color: '#ffffff', fontSize: 24, fontWeight: 'bold' });\n"
    "NativeUI.appendChild(root, title);\n"
    "const body = NativeUI.createNode('Text');\n"
    "NativeUI.setProps(body, { text: msg, color: '#ffd9d9', fontSize: 14, width: W - 48, numberOfLines: 20 });\n"
    "NativeUI.appendChild(root, body);\n"
    "const hint = NativeUI.createNode('Text');\n"
    "NativeUI.setProps(hint, { text: 'fix the source and save to reload (or press R)', color: '#ff9b9b', fontSize: 12 "
    "});\n"
    "NativeUI.appendChild(root, hint);\n"
    "NativeUI.setRoot(root);\n"
    "NativeUI.commit();\n";

/*----------------------------------------------------------------------------------------------------------------------
 - Functions: Private — file + JS helpers
 ---------------------------------------------------------------------------------------------------------------------*/

/**
 * @brief Reads an entire file into a newly allocated, null-terminated buffer.
 *
 * @param[in]  path     Filesystem path to read.
 * @param[out] out_len  Receives the byte length (excluding the appended terminator).
 *
 * @return Heap buffer the caller must free(), or NULL if the file could not be read.
 */
static char* read_file(const char* path, size_t* out_len)
{
    FILE* f = fopen(path, "rb");
    if (!f)
    {
        return NULL;
    }
    fseek(f, 0, SEEK_END);
    const long n = ftell(f);
    fseek(f, 0, SEEK_SET);
    if (n < 0)
    {
        fclose(f);
        return NULL;
    }
    char* buf = (char*)malloc((size_t)n + 1);
    if (!buf)
    {
        fclose(f);
        return NULL;
    }
    const size_t rd = fread(buf, 1, (size_t)n, f);
    fclose(f);
    buf[rd] = '\0';
    *out_len = rd;
    return buf;
}

/**
 * @brief Returns true when a path ends in ".qbc" (a compiled bytecode blob).
 *
 * @param[in] path  File path.
 *
 * @return true for a bytecode path, false for JS source.
 */
static bool is_bytecode_path(const char* path)
{
    const size_t n = strlen(path);
    return n >= 4 && strcmp(path + n - 4, ".qbc") == 0;
}

/**
 * @brief Minimal console.log implementation printing space-separated arguments to stdout.
 *
 * @param[in] ctx       QuickJS context.
 * @param[in] this_val  JS `this` (unused).
 * @param[in] argc      Argument count.
 * @param[in] argv      Argument values.
 *
 * @return JS_UNDEFINED, or JS_EXCEPTION if an argument cannot be stringified.
 */
static JSValue host_console_log(JSContext* ctx, JSValueConst this_val, int argc, JSValueConst* argv)
{
    (void)this_val;
    for (int i = 0; i < argc; i++)
    {
        const char* str = JS_ToCString(ctx, argv[i]);
        if (!str)
        {
            return JS_EXCEPTION;
        }
        printf("%s%s", i ? " " : "", str);
        JS_FreeCString(ctx, str);
    }
    printf("\n");
    return JS_UNDEFINED;
}

/**
 * @brief Installs a minimal `console` (log/warn/error all map to stdout) onto the global scope.
 *
 * @param[in] ctx  QuickJS context.
 */
static void host_install_console(JSContext* ctx)
{
    JSValue global = JS_GetGlobalObject(ctx);
    JSValue console = JS_NewObject(ctx);
    JSValue log = JS_NewCFunction(ctx, host_console_log, "log", 1);

    JS_SetPropertyStr(ctx, console, "log", JS_DupValue(ctx, log));
    JS_SetPropertyStr(ctx, console, "warn", JS_DupValue(ctx, log));
    JS_SetPropertyStr(ctx, console, "error", log);
    JS_SetPropertyStr(ctx, global, "console", console);
    JS_FreeValue(ctx, global);
}

/**
 * @brief Injects a `screen` global ({ width, height, scale }) so the app can size its root.
 *
 * @param[in] ctx     QuickJS context.
 * @param[in] width   Framebuffer width in physical pixels.
 * @param[in] height  Framebuffer height in physical pixels.
 * @param[in] scale   DPI scale factor.
 */
static void host_install_screen(JSContext* ctx, int width, int height, float scale)
{
    JSValue global = JS_GetGlobalObject(ctx);
    JSValue screen = JS_NewObject(ctx);

    JS_SetPropertyStr(ctx, screen, "width", JS_NewInt32(ctx, width));
    JS_SetPropertyStr(ctx, screen, "height", JS_NewInt32(ctx, height));
    JS_SetPropertyStr(ctx, screen, "scale", JS_NewFloat64(ctx, (double)scale));
    JS_SetPropertyStr(ctx, global, "screen", screen);
    JS_FreeValue(ctx, global);
}

/**
 * @brief Reports an uncaught JS exception (message + stack) to stderr and frees the result.
 *
 * @param[in] ctx     QuickJS context.
 * @param[in] result  The value returned by JS_Eval / er_bridge_run_bytecode (consumed).
 *
 * @return true on clean evaluation; false if an exception propagated.
 */
static bool host_report(JSContext* ctx, JSValue result)
{
    bool ok = true;
    if (JS_IsException(result))
    {
        JSValue exc = JS_GetException(ctx);
        const char* msg = JS_ToCString(ctx, exc);
        fprintf(stderr, "JS exception: %s\n", msg ? msg : "(unknown)");

        JSValue stack = JS_GetPropertyStr(ctx, exc, "stack");
        const char* st = JS_IsUndefined(stack) ? NULL : JS_ToCString(ctx, stack);
        if (st)
        {
            fprintf(stderr, "%s\n", st);
        }

        /* Capture message + stack for the error overlay (er_host_show_error). */
        snprintf(s_last_error, sizeof(s_last_error), "%s%s%s", msg ? msg : "(unknown)", st ? "\n\n" : "", st ? st : "");

        if (msg)
        {
            JS_FreeCString(ctx, msg);
        }
        if (st)
        {
            JS_FreeCString(ctx, st);
        }
        JS_FreeValue(ctx, stack);
        JS_FreeValue(ctx, exc);
        ok = false;
    }
    JS_FreeValue(ctx, result);
    return ok;
}

/**
 * @brief Runs an app from either JS source or a compiled bytecode blob, reporting exceptions.
 *
 * @param[in] ctx       QuickJS context.
 * @param[in] src       Source text, or bytecode bytes when is_bytecode is true.
 * @param[in] len       Byte length of src.
 * @param[in] name      Display name used in stack traces (source path).
 * @param[in] bytecode  true to load src as a QuickJS bytecode blob (JS_ReadObject).
 *
 * @return true on clean evaluation; false if an exception propagated.
 */
static bool host_run(JSContext* ctx, const char* src, size_t len, const char* name, bool bytecode)
{
    JSValue result = bytecode ? er_bridge_run_bytecode(ctx, (const uint8_t*)src, len)
                              : JS_Eval(ctx, src, len, name, JS_EVAL_TYPE_GLOBAL);
    return host_report(ctx, result);
}

/**
 * @brief Creates a fresh QuickJS context on the host's runtime and installs console, screen, and the
 *        NativeUI bridge. Used at startup and on every live reload.
 *
 * @param[in,out] host  Host whose ctx field is (re)created.
 */
static void host_install_globals(ErHost* host)
{
    host->ctx = JS_NewContext(host->rt);
    host_install_console(host->ctx);
    host_install_screen(host->ctx, host->phys_w, host->phys_h, host->dpi_scale);
    er_bridge_install(host->ctx);
}

/*----------------------------------------------------------------------------------------------------------------------
 - Functions: Public
 ---------------------------------------------------------------------------------------------------------------------*/

bool er_host_start(const ErHostConfig* cfg, ErHost* host)
{
    memset(host, 0, sizeof(*host));

    SDL_SetMainReady();
    if (SDL_Init(SDL_INIT_VIDEO) != 0)
    {
        SDL_Log("SDL_Init failed: %s", SDL_GetError());
        return false;
    }

    host->window = SDL_CreateWindow(cfg->title ? cfg->title : "embedded-react",
                                    SDL_WINDOWPOS_CENTERED,
                                    SDL_WINDOWPOS_CENTERED,
                                    cfg->width,
                                    cfg->height,
                                    SDL_WINDOW_SHOWN | SDL_WINDOW_ALLOW_HIGHDPI);
    if (!host->window)
    {
        SDL_Log("SDL_CreateWindow failed: %s", SDL_GetError());
        SDL_Quit();
        return false;
    }

    host->renderer = SDL_CreateRenderer(host->window, -1, SDL_RENDERER_ACCELERATED | SDL_RENDERER_PRESENTVSYNC);
    if (!host->renderer)
    {
        SDL_Log("SDL_CreateRenderer failed: %s", SDL_GetError());
        SDL_DestroyWindow(host->window);
        SDL_Quit();
        return false;
    }

    host->phys_w = cfg->width;
    host->phys_h = cfg->height;
    SDL_GetRendererOutputSize(host->renderer, &host->phys_w, &host->phys_h);
    host->dpi_scale = (float)host->phys_w / (float)cfg->width;

    if (!er_sdl_backend_init(host->renderer, host->phys_w, host->phys_h))
    {
        SDL_Log("er_sdl_backend_init failed");
        SDL_DestroyRenderer(host->renderer);
        SDL_DestroyWindow(host->window);
        SDL_Quit();
        return false;
    }

    /* Hand the app's baked assets (images + fonts) to the engine now that the backend init above set
     * up the registries. Generated by `npm run build`; absent before the first build. */
#if defined(ER_HAVE_BAKED_ASSETS)
    er_register_assets();
#endif

    /* Boot QuickJS and publish the bridge + host globals. */
    host->rt = JS_NewRuntime();
    host_install_globals(host);

    host->running = true;
    host->prev_ticks = SDL_GetTicks();
    return true;
}

bool er_host_reload(ErHost* host, const char* explicit_path)
{
    /* Live reload (full remount): drop the JS context — freeing the whole React tree, the bridge's
     * GC-rooted registries, event handlers, and timers — reset the engine to an empty scene, then
     * bring up a fresh context and re-run the app. Component state is intentionally not preserved
     * (that's Fast Refresh, a later phase — see /SIMULATOR.md). Registered images/fonts survive the
     * reset, so baked assets keep resolving. */
    if (host->ctx)
    {
        JS_FreeContext(host->ctx);
        host->ctx = NULL;
    }
    er_reset();
    host_install_globals(host);
    return er_host_load_app(host, explicit_path);
}

void er_host_show_error(ErHost* host)
{
    /* RN-redbox style: clear the (possibly half-built) scene, publish the last captured error text as
     * a global, and run the built-in error app in the current context so the failure is on screen
     * instead of leaving a blank/stale window. The next successful reload replaces it. */
    er_reset();
    JSValue global = JS_GetGlobalObject(host->ctx);
    JS_SetPropertyStr(host->ctx, global, "__error", JS_NewString(host->ctx, s_last_error));
    JS_FreeValue(host->ctx, global);
    host_run(host->ctx, k_error_app, strlen(k_error_app), "<error-overlay>", false);
    er_bridge_pump(host->ctx);
}

bool er_host_load_app(ErHost* host, const char* explicit_path)
{
    /* Choose the app to run, in priority order:
     *   1. an explicit path (.qbc = bytecode, else source),
     *   2. the compiled bytecode bundle (app.bundle.qbc) next to the executable — the MCU load path,
     *   3. the source bundle (app.bundle.js) next to the executable,
     *   4. the built-in fallback JS app.
     */
    char* loaded = NULL;
    const char* app_src = k_default_app;
    size_t app_len = strlen(k_default_app);
    const char* app_name = "<builtin-app>";
    bool app_bytecode = false;

    if (explicit_path)
    {
        size_t len = 0;
        loaded = read_file(explicit_path, &len);
        if (loaded)
        {
            app_src = loaded;
            app_len = len;
            app_name = explicit_path;
            app_bytecode = is_bytecode_path(explicit_path);
        }
        else
        {
            SDL_Log("could not read '%s'; falling back to the bundled app", explicit_path);
        }
    }
    if (!loaded)
    {
        char* base = SDL_GetBasePath();
        if (base)
        {
            char path[1024];
            size_t len = 0;
            /* Prefer the compiled bytecode blob (no parser, faster boot) over the source bundle. */
            snprintf(path, sizeof(path), "%sapp.bundle.qbc", base);
            loaded = read_file(path, &len);
            if (loaded)
            {
                app_src = loaded;
                app_len = len;
                app_name = "app.bundle.qbc";
                app_bytecode = true;
            }
            else
            {
                snprintf(path, sizeof(path), "%sapp.bundle.js", base);
                loaded = read_file(path, &len);
                if (loaded)
                {
                    app_src = loaded;
                    app_len = len;
                    app_name = "app.bundle.js";
                }
            }
            SDL_free(base);
        }
    }

    /* Make the chosen path explicit — otherwise a silent fall-back from bytecode to source (e.g.
       the precompiler wasn't built, so app.bundle.qbc is missing) looks identical at runtime. */
    SDL_Log("running %s (%s)", app_name, app_bytecode ? "bytecode" : "source");

    const bool app_ok = host_run(host->ctx, app_src, app_len, app_name, app_bytecode);
    free(loaded);

    /* Settle any Promises / mount-time microtasks the app queued before the first paint. */
    if (app_ok)
    {
        er_bridge_pump(host->ctx);
    }
    return app_ok;
}

int er_host_event_px(const ErHost* host, int logical)
{
    return (int)((float)logical * host->dpi_scale + 0.5f);
}

bool er_host_step(ErHost* host)
{
    SDL_Event ev;
    while (SDL_PollEvent(&ev))
    {
        if (ev.type == SDL_QUIT)
        {
            host->running = false;
        }
        else if (ev.type == SDL_KEYDOWN && ev.key.keysym.sym == SDLK_ESCAPE)
        {
            host->running = false;
        }
        else if (ev.type == SDL_KEYDOWN && ev.key.keysym.sym == SDLK_r)
        {
            host->reload_requested = true; /* the simulator acts on this; the demo ignores it */
        }
        else if (ev.type == SDL_MOUSEBUTTONDOWN && ev.button.button == SDL_BUTTON_LEFT)
        {
            embedded_renderer_touch(
                0, ER_TOUCH_DOWN, er_host_event_px(host, ev.button.x), er_host_event_px(host, ev.button.y));
        }
        else if (ev.type == SDL_MOUSEBUTTONUP && ev.button.button == SDL_BUTTON_LEFT)
        {
            embedded_renderer_touch(
                0, ER_TOUCH_UP, er_host_event_px(host, ev.button.x), er_host_event_px(host, ev.button.y));
        }
        else if (ev.type == SDL_MOUSEMOTION && (ev.motion.state & SDL_BUTTON_LMASK))
        {
            embedded_renderer_touch(
                0, ER_TOUCH_MOVE, er_host_event_px(host, ev.motion.x), er_host_event_px(host, ev.motion.y));
        }
    }

    /* Service Promises and setTimeout/setInterval before painting, so timer/async-driven state
       updates land in this frame's commit. The engine clock used by timers was advanced by last
       frame's embedded_renderer_tick. */
    er_bridge_pump(host->ctx);

    er_commit();
    er_sdl_present();

    const uint32_t now = SDL_GetTicks();
    embedded_renderer_tick(now - host->prev_ticks);
    host->prev_ticks = now;

    return host->running;
}

void er_host_run(ErHost* host)
{
    host->prev_ticks = SDL_GetTicks();
    while (er_host_step(host))
    {
        /* step until quit */
    }
}

void er_host_shutdown(ErHost* host)
{
    if (host->ctx)
    {
        JS_FreeContext(host->ctx);
        host->ctx = NULL;
    }
    if (host->rt)
    {
        JS_FreeRuntime(host->rt);
        host->rt = NULL;
    }
    er_sdl_backend_destroy();
    if (host->renderer)
    {
        SDL_DestroyRenderer(host->renderer);
        host->renderer = NULL;
    }
    if (host->window)
    {
        SDL_DestroyWindow(host->window);
        host->window = NULL;
    }
    SDL_Quit();
}
