/*
 * Copyright 2026 Cory Lamming
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * er-bridge-quickjs-compile — bytecode precompiler for the JS bundle (Flow A).
 *
 * Compiles a JS source bundle (esbuild output) to QuickJS bytecode using the SAME pinned QuickJS
 * build the host links, so the blob is load-compatible. The host loads it with JS_ReadObject +
 * JS_EvalFunction instead of parsing source on boot — the parser and source text never ship, which
 * cuts boot time and RAM working-set. This is for the MCU hosts (ESP32-S3 / STM32H7).
 *
 * NOTE — this is NOT the Flow B "AOT compiler". This only moves the *parse* step from boot to build
 * time; the QuickJS VM still interprets the bytecode at runtime (QuickJS is still linked and running).
 * Flow B is a separate effort that compiles JSX straight to C against er_scene.h and removes QuickJS
 * entirely (for MCUs without the external RAM to host the VM). See PLAN.md.
 *
 * Usage:
 *   er-bridge-quickjs-compile <input.js> <output.qbc>                  # raw bytecode blob
 *   er-bridge-quickjs-compile <input.js> <output.c> <array_name>       # C source: byte array + len
 *
 * The C-array form is what an MCU build embeds in flash; the raw form is handy for a host that
 * loads a blob from storage at runtime.
 */

#include "quickjs.h"

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/*----------------------------------------------------------------------------------------------------------------------
 - Functions: Private
 ---------------------------------------------------------------------------------------------------------------------*/

/**
 * @brief Reads an entire file into a newly allocated, null-terminated buffer.
 *
 * @param[in]  path     Filesystem path to read.
 * @param[out] out_len  Receives the byte length (excluding the appended terminator).
 *
 * @return Heap buffer the caller must free(), or NULL if the file could not be read.
 */
static char* read_file(const char* path, size_t* out_len)
{
    FILE* f = fopen(path, "rb");
    if (!f)
    {
        return NULL;
    }
    fseek(f, 0, SEEK_END);
    const long n = ftell(f);
    fseek(f, 0, SEEK_SET);
    if (n < 0)
    {
        fclose(f);
        return NULL;
    }
    char* buf = (char*)malloc((size_t)n + 1);
    if (!buf)
    {
        fclose(f);
        return NULL;
    }
    const size_t rd = fread(buf, 1, (size_t)n, f);
    fclose(f);
    buf[rd] = '\0';
    *out_len = rd;
    return buf;
}

/**
 * @brief Writes bytecode as a raw binary blob.
 *
 * @param[in] path  Output path.
 * @param[in] buf   Bytecode bytes.
 * @param[in] len   Byte count.
 *
 * @return true on success.
 */
static bool write_raw(const char* path, const uint8_t* buf, size_t len)
{
    FILE* f = fopen(path, "wb");
    if (!f)
    {
        return false;
    }
    const size_t wr = fwrite(buf, 1, len, f);
    fclose(f);
    return wr == len;
}

/**
 * @brief Writes bytecode as a C source file: a `const uint8_t name[]` + `const unsigned int name_len`.
 *
 * @param[in] path  Output path.
 * @param[in] name  C identifier for the array (and `<name>_len`).
 * @param[in] src   Source path (recorded in a comment).
 * @param[in] buf   Bytecode bytes.
 * @param[in] len   Byte count.
 *
 * @return true on success.
 */
static bool write_c_array(const char* path, const char* name, const char* src, const uint8_t* buf, size_t len)
{
    FILE* f = fopen(path, "w");
    if (!f)
    {
        return false;
    }
    fprintf(f, "/* Generated by er-bridge-quickjs-compile from %s. QuickJS bytecode — do not edit. */\n", src);
    fprintf(f, "#include <stdint.h>\n\n");
    fprintf(f, "const unsigned int %s_len = %zuu;\n", name, len);
    fprintf(f, "const uint8_t %s[%zu] = {\n   ", name, len);
    for (size_t i = 0; i < len; i++)
    {
        fprintf(f, " 0x%02x,", buf[i]);
        if ((i & 15U) == 15U)
        {
            fprintf(f, "\n   ");
        }
    }
    fprintf(f, "\n};\n");
    fclose(f);
    return true;
}

/**
 * @brief Prints a pending JS exception (message + stack) to stderr.
 *
 * @param[in] ctx  Context whose current exception should be reported.
 */
static void report_exception(JSContext* ctx)
{
    JSValue exc = JS_GetException(ctx);
    const char* msg = JS_ToCString(ctx, exc);
    fprintf(stderr, "compile error: %s\n", msg ? msg : "(unknown)");
    if (msg)
    {
        JS_FreeCString(ctx, msg);
    }
    JSValue stack = JS_GetPropertyStr(ctx, exc, "stack");
    if (!JS_IsUndefined(stack))
    {
        const char* st = JS_ToCString(ctx, stack);
        if (st)
        {
            fprintf(stderr, "%s\n", st);
            JS_FreeCString(ctx, st);
        }
    }
    JS_FreeValue(ctx, stack);
    JS_FreeValue(ctx, exc);
}

/*----------------------------------------------------------------------------------------------------------------------
 - Functions: Public
 ---------------------------------------------------------------------------------------------------------------------*/

/**
 * @brief Entry point: compiles a JS bundle to QuickJS bytecode.
 *
 * @param[in] argc  Argument count.
 * @param[in] argv  argv[1] = input JS, argv[2] = output path, argv[3] = optional C array name.
 *
 * @return 0 on success; non-zero on a usage, I/O, or compile error.
 */
int main(int argc, char** argv)
{
    if (argc < 3)
    {
        fprintf(stderr, "usage: %s <input.js> <output> [c_array_name]\n", argv[0]);
        return 2;
    }
    const char* in_path = argv[1];
    const char* out_path = argv[2];
    const char* array_name = (argc >= 4) ? argv[3] : NULL;

    size_t src_len = 0;
    char* src = read_file(in_path, &src_len);
    if (!src)
    {
        fprintf(stderr, "could not read '%s'\n", in_path);
        return 2;
    }

    JSRuntime* rt = JS_NewRuntime();
    JSContext* ctx = JS_NewContext(rt);

    /* COMPILE_ONLY returns the program's function bytecode without running it (so the bundle's
       references to NativeUI/screen/console are not resolved here — only at load time). */
    JSValue obj = JS_Eval(ctx, src, src_len, in_path, JS_EVAL_TYPE_GLOBAL | JS_EVAL_FLAG_COMPILE_ONLY);
    free(src);

    int status = 0;
    if (JS_IsException(obj))
    {
        report_exception(ctx);
        status = 1;
    }
    else
    {
        size_t bc_len = 0;
        uint8_t* bc = JS_WriteObject(ctx, &bc_len, obj, JS_WRITE_OBJ_BYTECODE);
        if (!bc)
        {
            fprintf(stderr, "JS_WriteObject failed\n");
            status = 1;
        }
        else
        {
            const bool ok =
                array_name ? write_c_array(out_path, array_name, in_path, bc, bc_len) : write_raw(out_path, bc, bc_len);
            if (!ok)
            {
                fprintf(stderr, "could not write '%s'\n", out_path);
                status = 1;
            }
            else
            {
                printf("compiled %s -> %s (%zu bytes bytecode)\n", in_path, out_path, bc_len);
            }
            js_free(ctx, bc);
        }
    }

    JS_FreeValue(ctx, obj);
    JS_FreeContext(ctx);
    JS_FreeRuntime(rt);
    return status;
}
