#!/usr/bin/env python3
"""
gen_image.py — Bake PNG (or any Pillow-readable) images into a C source file for embedded-react.

The engine's image registry (engine/rendering/image_registry.c) renders Image nodes from
**premultiplied ARGB8888** pixel buffers referenced by pointer (never copied), so a build-time bake to
a flash-resident `const uint32_t[]` needs no runtime decoder and costs zero RAM. This mirrors the
font/bytecode bake pattern: decode on the host, ship raw pixels in the image.

Output
------
A single .c file declaring one `static const uint32_t <name>_px[]` per image plus a public
`er_register_baked_images(void)` that calls er_image_load() for each, and a sibling .h with that
prototype. Pixels are premultiplied ARGB8888: pixel = (A<<24) | (Ra<<16) | (Ga<<8) | Ba, where the
colour channels are alpha-premultiplied (Ra = round(R*A/255), ...).

Usage
-----
    python tools/image-converter/gen_image.py \\
        --out demos/thermostat/assets/image_data.c \\
        sun=demos/thermostat/assets/sun.png \\
        cloud=demos/thermostat/assets/cloud.png

Each positional arg is `name=path`; `name` is the asset name an <Image imageName="name"> looks up
(must fit ER_IMAGE_NAME_MAX = 63 chars). Resize/scaling is done at render time by the engine, so bake
at whatever source resolution you want to ship.

Dependencies
    pip install Pillow
"""

import argparse
import os
import re
import sys

try:
    from PIL import Image
except ImportError:
    sys.exit("gen_image.py needs Pillow:  pip install Pillow")


def c_ident(name):
    """Sanitizes an asset name into a C identifier fragment."""
    ident = re.sub(r"[^0-9a-zA-Z_]", "_", name)
    if ident and ident[0].isdigit():
        ident = "_" + ident
    return ident or "_img"


def premultiply_argb(img):
    """Returns (w, h, [uint32]) of premultiplied ARGB8888 pixels for a Pillow image."""
    img = img.convert("RGBA")
    w, h = img.size
    data = img.tobytes()  # RGBA bytes, row-major
    out = []
    for i in range(0, len(data), 4):
        r, g, b, a = data[i], data[i + 1], data[i + 2], data[i + 3]
        # Premultiply the colour channels by alpha (round-to-nearest).
        rp = (r * a + 127) // 255
        gp = (g * a + 127) // 255
        bp = (b * a + 127) // 255
        out.append((a << 24) | (rp << 16) | (gp << 8) | bp)
    return w, h, out


def emit_array(f, ident, pixels):
    """Writes a `static const uint32_t <ident>_px[] = { ... };` array, 8 values per line."""
    f.write(f"static const uint32_t {ident}_px[] = {{\n")
    for i in range(0, len(pixels), 8):
        row = ", ".join(f"0x{p:08X}u" for p in pixels[i : i + 8])
        f.write(f"    {row},\n")
    f.write("};\n\n")


def main():
    ap = argparse.ArgumentParser(description="Bake images into a C source file for embedded-react.")
    ap.add_argument("--out", required=True, help="Output .c path (a sibling .h is written too).")
    ap.add_argument("images", nargs="+", help="One or more name=path.png entries.")
    args = ap.parse_args()

    assets = []
    for entry in args.images:
        if "=" not in entry:
            sys.exit(f"bad image arg '{entry}' — expected name=path")
        name, path = entry.split("=", 1)
        name = name.strip()
        if len(name) > 63:
            sys.exit(f"asset name '{name}' exceeds ER_IMAGE_NAME_MAX (63)")
        if not os.path.isfile(path):
            sys.exit(f"image not found: {path}")
        w, h, px = premultiply_argb(Image.open(path))
        assets.append((name, c_ident(name), w, h, px))

    out_c = args.out
    out_h = os.path.splitext(out_c)[0] + ".h"
    guard = "ER_" + c_ident(os.path.basename(out_h)).upper()

    with open(out_h, "w", encoding="utf-8", newline="\n") as f:
        f.write("/* Generated by tools/image-converter/gen_image.py — DO NOT EDIT. */\n")
        f.write(f"#ifndef {guard}\n#define {guard}\n\n")
        f.write("#ifdef __cplusplus\nextern \"C\"\n{\n#endif\n\n")
        f.write("    /** @brief Registers every baked image with the engine image registry (call once at boot). */\n")
        f.write("    void er_register_baked_images(void);\n\n")
        f.write("#ifdef __cplusplus\n}\n#endif\n\n")
        f.write(f"#endif\n")

    with open(out_c, "w", encoding="utf-8", newline="\n") as f:
        f.write("/* Generated by tools/image-converter/gen_image.py — DO NOT EDIT. */\n")
        f.write("/* Premultiplied ARGB8888, row-major, referenced by pointer by the image registry. */\n\n")
        f.write(f"#include \"{os.path.basename(out_h)}\"\n\n")
        f.write("#include \"er_scene.h\" /* er_image_load */\n\n")
        f.write("#include <stdint.h>\n\n")
        for (name, ident, w, h, px) in assets:
            f.write(f"/* \"{name}\" — {w}x{h} */\n")
            emit_array(f, ident, px)
        f.write("void er_register_baked_images(void)\n{\n")
        for (name, ident, w, h, px) in assets:
            f.write(f"    er_image_load(\"{name}\", {ident}_px, {w}, {h});\n")
        f.write("}\n")

    total = sum(w * h for (_, _, w, h, _) in assets)
    print(f"gen_image.py: baked {len(assets)} image(s) ({total} px) -> {out_c} (+ {os.path.basename(out_h)})")
    for (name, _, w, h, _) in assets:
        print(f"  {name}: {w}x{h}")


if __name__ == "__main__":
    main()
