/* Generated by tools/image-converter/gen_image.py — DO NOT EDIT. */
#ifndef ER_IMAGE_DATA_H
#define ER_IMAGE_DATA_H

#ifdef __cplusplus
extern "C"
{
#endif

    /** @brief Registers every baked image with the engine image registry (call once at boot). */
    void er_register_baked_images(void);

#ifdef __cplusplus
}
#endif

#endif
